# Gap 5 (docs/TEST-PLAN.md): paired with blade07. See sibling manifest for context.
---
apiVersion: composition.krateo.io/v0-3-3
kind: BaremetalHost
metadata:
  name: blade08
  namespace: openstack
spec:
  nodeName: blade08
  nodeNamespace: openstack
  nodeUuid: daef0a77-1db5-4181-a577-bcfb31becc72
  parentNode: 5113ab44-faf2-4f76-bb41-ea8b14b7aa92
  driver: redfish
  driver_info:
    redfish_address: http://172.19.74.11:8000
    redfish_verify_ca: false
    redfish_username: ironic
    redfish_password: baremetal
    redfish_system_id: /redfish/v1/Systems/blade08
  ports:
    - address: "00:60:2f:38:81:01"
      pxe_enabled: true
    - address: "00:60:2f:38:81:02"
      pxe_enabled: false
  enableInspection: true
  image:
    source: http://172.19.74.1:8089/debian-13-genericcloud-amd64.qcow2
    checksum: http://172.19.74.1:8089/CHECKSUM
  configDrive:
    metaData:
      uuid: daef0a77-1db5-4181-a577-bcfb31becc72
      hostname: blade08
  online: true
